server:
  port: ${PORT:5000}
  servlet:
    session:
      cookie:
        http-only: true

spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

    hikari:
      auto-commit: true
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 5000
      max-lifetime: 1000
      connection-init-sql: "SET application_name = 'PostgreSQL JDBC Driver';"

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: off