server:
  port: ${PORT:5000}
  servlet:
    session:
      cookie:
        http-only: true

spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

    tomcat:
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      max-active: 15
      max-idle: 10
      max-wait: 8000

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: off