INSERT INTO role (id, name) VALUES (1, 'ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO role (id, name) VALUES (2, 'ROLE_CLIENT') ON CONFLICT DO NOTHING;
INSERT INTO role (id, name) VALUES (3, 'ROLE_OWNER') ON CONFLICT DO NOTHING;
INSERT INTO role (id, name) VALUES (4, 'ROLE_ARTIST') ON CONFLICT DO NOTHING;