INSERT INTO role (id, authority) VALUES (1, 'ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO role (id, authority) VALUES (2, 'ROLE_ACTIVE_USER') ON CONFLICT DO NOTHING;
INSERT INTO role (id, authority) VALUES (3, 'ROLE_EXPERT') ON CONFLICT DO NOTHING;